apiVersion: constraints.gatekeeper.sh/v1beta1
kind: WorkloadRecommendation
metadata:
  name: workload-recommendation
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
      - apiGroups: ["autoscaling"]
        kinds: ["Scale"]
