---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finops-gatekeeper-provider
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finops-gatekeeper-provider
  template:
    metadata:
      labels:
        app: finops-gatekeeper-provider
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/lch_test/finops-gatekeeper-provider:v0.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls
              mountPath: /certs         # 目标路径
              readOnly: true                    # 建议只读
          name: finops-gatekeeper-provider
          ports:
            - containerPort: 8090
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: tls
          secret:
            secretName: finops-external-data-secret
      nodeSelector:
        kubernetes.io/os: linux