apiVersion: v1
kind: Service
metadata:
  name: finops-gatekeeper-provider
  namespace: kube-system
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: finops-gatekeeper-provider
  sessionAffinity: None